"""The customer a row belongs to.

Deliberately thin. A tenant in this boilerplate is an isolation boundary and
nothing else — no plan, no quota, no billing relationship — because those are
the parts every application models differently and the boundary is the part
none of them can get wrong. Add the columns your product needs; do not add
anything the *policies* would then have to read, because a policy predicate
runs on every row of every query and wants to be one equality test.

## Why the table is itself tenant-scoped

`tenants` carries a policy comparing `id` against `app_current_tenant_id()`,
so a bound connection sees exactly one row: its own. That is not symmetry for
its own sake. Without it, `SELECT slug FROM tenants` is an enumeration of
every customer this deployment has, available to anyone who reaches a code
path that reads the table — and the list of who a vendor sells to is the one
piece of cross-tenant data that leaks without anybody noticing a row count.

The consequence is that an administrative process which has to see all
tenants runs as a role with `BYPASSRLS` and no part in serving requests. See
`docs/multi-tenancy.md`.
"""

import uuid
from datetime import datetime
from typing import Final

from sqlalchemy import UUID, Boolean, DateTime, String, Table, event, func
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.engine import Connection
from sqlalchemy.orm import Mapped, mapped_column

from src.database import Base


class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    #: The stable, human-readable handle: a subdomain, a path segment, the
    #: thing an operator types. Unique globally rather than per-tenant for the
    #: obvious reason, and 63 characters because that is a DNS label.
    #:
    #: Note what this means under the policy above: a bound connection cannot
    #: check whether a slug is taken, because it cannot see the rows that
    #: would take it. Provisioning is therefore not a tenant-scoped operation
    #: and does not run through the request path — see `docs/multi-tenancy.md`.
    slug: Mapped[str] = mapped_column(String(63), unique=True, nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    #: Soft suspension. Not enforced by a policy: a suspended tenant's rows
    #: are still its own, and folding "does this row belong to you" together
    #: with "are you allowed in today" would make reactivating a customer a
    #: data-visibility change. The check belongs at the edge.
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


#: The tenant every row that predates multi-tenancy belongs to.
#:
#: A fixed UUID rather than one generated by the migration, because three
#: things have to agree on it and only one of them runs at migration time:
#: Alembic `0008`, which backfills `users.tenant_id` and `refresh_tokens
#: .tenant_id` with it; the `after_create` hook below, for a database built by
#: `Base.metadata.create_all` instead of by migrations; and the test suite,
#: which runs inside it. A generated id would mean a staging database and a
#: developer's laptop disagreeing about which tenant the seed data is in.
#:
#: It is an ordinary tenant in every other respect. Nothing special-cases it,
#: no policy exempts it, and a deployment that never had single-tenant data
#: can delete it.
DEFAULT_TENANT_ID: Final[uuid.UUID] = uuid.UUID("00000000-0000-0000-0000-000000000001")
DEFAULT_TENANT_SLUG: Final[str] = "default"
DEFAULT_TENANT_NAME: Final[str] = "Default tenant"


@event.listens_for(Tenant.__table__, "after_create")
def _seed_default_tenant(target: Table, connection: Connection, **_: object) -> None:
    """Insert the bootstrap tenant whenever this table is created from metadata.

    Only for `create_all`. Migration `0008` inserts the same row itself, and
    on a migrated database this hook never fires because the table already
    exists. It is here so that a test or a throwaway database built straight
    from the mappers is not missing the one row every foreign key in the
    fixtures points at.

    `ON CONFLICT DO NOTHING` because a schema can be created more than once
    against the same database in a test session, and a duplicate-key error
    during `create_all` is a confusing way to learn that.
    """
    connection.execute(
        pg_insert(target)
        .values(
            id=DEFAULT_TENANT_ID,
            slug=DEFAULT_TENANT_SLUG,
            name=DEFAULT_TENANT_NAME,
        )
        .on_conflict_do_nothing(index_elements=["id"])
    )
